var EntityLogicalName = "account";
var Form_8448b78f_8f42_454e_8e2a_f8196b0419af_Properties = {
address1_composite: "address1_composite"
,address1_freighttermscode: "address1_freighttermscode"
,address1_shippingmethodcode: "address1_shippingmethodcode"
,creditlimit: "creditlimit"
,creditonhold: "creditonhold"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotfax: "donotfax"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,fax: "fax"
,industrycode: "industrycode"
,lastusedincampaign: "lastusedincampaign"
,name: "name"
,numberofemployees: "numberofemployees"
,originatingleadid: "originatingleadid"
,ownerid: "ownerid"
,ownershipcode: "ownershipcode"
,parentaccountid: "parentaccountid"
,paymenttermscode: "paymenttermscode"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,primarycontactid: "primarycontactid"
,revenue: "revenue"
,sic: "sic"
,telephone1: "telephone1"
,tickersymbol: "tickersymbol"
,transactioncurrencyid: "transactioncurrencyid"
,websiteurl: "websiteurl"
};

var Form_8448b78f_8f42_454e_8e2a_f8196b0419af_Controls = {
accountcasessgrid: "accountcasessgrid"
,accountopportunitiesgrid: "accountopportunitiesgrid"
,address1_composite: "address1_composite"
,address1_freighttermscode: "address1_freighttermscode"
,address1_shippingmethodcode: "address1_shippingmethodcode"
,ChildAccounts: "ChildAccounts"
,contactquickform: "contactquickform"
,Contacts: "Contacts"
,creditlimit: "creditlimit"
,creditonhold: "creditonhold"
,description: "description"
,donotbulkemail: "donotbulkemail"
,donotemail: "donotemail"
,donotfax: "donotfax"
,donotphone: "donotphone"
,donotpostalmail: "donotpostalmail"
,donotsendmm: "donotsendmm"
,fax: "fax"
,header_numberofemployees: "header_numberofemployees"
,header_ownerid: "header_ownerid"
,header_revenue: "header_revenue"
,industrycode: "industrycode"
,lastusedincampaign: "lastusedincampaign"
,mapcontrol: "mapcontrol"
,name: "name"
,notescontrol: "notescontrol"
,originatingleadid: "originatingleadid"
,ownershipcode: "ownershipcode"
,parentaccountid: "parentaccountid"
,paymenttermscode: "paymenttermscode"
,preferredcontactmethodcode: "preferredcontactmethodcode"
,primarycontactid: "primarycontactid"
,sic: "sic"
,subgrid_Entitlement: "subgrid_Entitlement"
,telephone1: "telephone1"
,tickersymbol: "tickersymbol"
,transactioncurrencyid: "transactioncurrencyid"
,websiteurl: "websiteurl"
};

