var EntityLogicalName = "opportunity";
var Form_a837e4a7_01b8_4f82_a475_be9abd67e667_Properties = {
budgetamount: "budgetamount"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,estimatedclosedate: "estimatedclosedate"
,estimatedvalue: "estimatedvalue"
,freightamount: "freightamount"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,name: "name"
,ownerid: "ownerid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,statuscode: "statuscode"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

var Form_a837e4a7_01b8_4f82_a475_be9abd67e667_Controls = {
budgetamount: "budgetamount"
,Competitors: "Competitors"
,currentsituation: "currentsituation"
,customerneed: "customerneed"
,description: "description"
,discountamount: "discountamount"
,discountpercentage: "discountpercentage"
,DynamicPropertiesList_LinkControl: "DynamicPropertiesList_LinkControl"
,freightamount: "freightamount"
,header_estimatedclosedate: "header_estimatedclosedate"
,header_estimatedvalue: "header_estimatedvalue"
,header_ownerid: "header_ownerid"
,header_statuscode: "header_statuscode"
,isrevenuesystemcalculated: "isrevenuesystemcalculated"
,name: "name"
,notescontrol: "notescontrol"
,opportunityproductsGrid: "opportunityproductsGrid"
,parentaccountid: "parentaccountid"
,parentcontactid: "parentcontactid"
,pricelevelid: "pricelevelid"
,ProductSuggestions_LinkControl: "ProductSuggestions_LinkControl"
,proposedsolution: "proposedsolution"
,purchaseprocess: "purchaseprocess"
,purchasetimeframe: "purchasetimeframe"
,Pursuit_Team: "Pursuit_Team"
,quote: "quote"
,Stakeholders: "Stakeholders"
,totalamount: "totalamount"
,totalamountlessfreight: "totalamountlessfreight"
,totallineitemamount: "totallineitemamount"
,totaltax: "totaltax"
,transactioncurrencyid: "transactioncurrencyid"
};

