var EntityLogicalName = "quotedetail";
var Form_1ff13845_48d3_4744_bc69_43b691931a6e_Properties = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,quantity: "quantity"
,requestdeliveryby: "requestdeliveryby"
,salesrepid: "salesrepid"
,shipto_city: "shipto_city"
,shipto_contactname: "shipto_contactname"
,shipto_country: "shipto_country"
,shipto_fax: "shipto_fax"
,shipto_freighttermscode: "shipto_freighttermscode"
,shipto_line1: "shipto_line1"
,shipto_line2: "shipto_line2"
,shipto_line3: "shipto_line3"
,shipto_name: "shipto_name"
,shipto_postalcode: "shipto_postalcode"
,shipto_stateorprovince: "shipto_stateorprovince"
,shipto_telephone: "shipto_telephone"
,tax: "tax"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
,willcall: "willcall"
};

var Form_1ff13845_48d3_4744_bc69_43b691931a6e_Controls = {
baseamount: "baseamount"
,extendedamount: "extendedamount"
,ispriceoverridden: "ispriceoverridden"
,isproductoverridden: "isproductoverridden"
,manualdiscountamount: "manualdiscountamount"
,priceperunit: "priceperunit"
,productdescription: "productdescription"
,productid: "productid"
,quantity: "quantity"
,requestdeliveryby: "requestdeliveryby"
,salesrepid: "salesrepid"
,shipto_city: "shipto_city"
,shipto_contactname: "shipto_contactname"
,shipto_country: "shipto_country"
,shipto_fax: "shipto_fax"
,shipto_freighttermscode: "shipto_freighttermscode"
,shipto_line1: "shipto_line1"
,shipto_line2: "shipto_line2"
,shipto_line3: "shipto_line3"
,shipto_name: "shipto_name"
,shipto_postalcode: "shipto_postalcode"
,shipto_stateorprovince: "shipto_stateorprovince"
,shipto_telephone: "shipto_telephone"
,tax: "tax"
,uomid: "uomid"
,volumediscountamount: "volumediscountamount"
,willcall: "willcall"
};

